[package]
name = "aoc15"
version = "0.1.0"
edition = "2021"
description = "Advent of Code 2015 puzzles in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "^0.2"